### PR TITLE
Add `README.md` and FMS schemas

### PR DESCRIPTION
**Pull request by J-Lentz**
Add a skeletal `README.md` as well as data table, diag table, and field table schemas.

### CODE REVIEW

**Review by uramirez8707 — APPROVED** [review]
Thanks. Looks good to me.

**Comment by uramirez8707** [comment]
Can this be merged so that I can start setting up the submodule in fms_yaml_tools?

**Comment by ceblanton** [comment]
Will do.  @J-Lentz , it would almost be nice to auto-merge PRs that are approved.

**Comment by J-Lentz** [comment]
> Will do. @J-Lentz , it would almost be nice to auto-merge PRs that are approved.

Thanks Chris. I've just enabled auto-merge for this repo.

**Pull request merged**
